[package]
name = "zstat"
version = "0.1.0"
authors = ["Dmitry Ulyanov <sillent1987@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.22"
serde = "1.0.103"
serde_json = "1.0.42"